import pkg from '/Users/brandon/Development/amazon-subscription-canceller/node_modules/playwright/index.js';
const { chromium } = pkg;
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1500, height: 1200 } });
const errs = [];
p.on('pageerror', e => errs.push('PAGEERROR ' + e.message));
p.on('console', m => { if (m.type() === 'error') errs.push('CONSOLE ' + m.text()); });
const r = await p.goto('http://localhost:4713/f/', { waitUntil: 'networkidle' });
console.log('status', r.status());
console.log('cards', await p.locator('.card').count());
console.log('mozz', await p.locator('#mozz').count());
console.log('slugs', (await p.locator('.slug').allTextContents()).join(','));
console.log(errs.join('\n'));
await b.close();
